"""Bounded, sequential Linux-Docker evaluations of pinned sidecars.

Source trees are read-only inputs. Every generated byte belongs in research/.work.
The admission check is also used while a container is running; only the container
created by this invocation can be stopped. No scientific claims follow from exit 0.
"""

from __future__ import annotations

import argparse
import ctypes
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path

sys.dont_write_bytecode = True
from inventory import REGISTRY, ROOT, WORK, load, save

GIB = 1024**3


def free_memory():
    if os.name == "nt":

        class MemoryStatus(ctypes.Structure):
            _fields_ = [
                ("length", ctypes.c_ulong),
                ("load", ctypes.c_ulong),
                *[
                    (name, ctypes.c_ulonglong)
                    for name in [
                        "total_phys",
                        "avail_phys",
                        "total_page",
                        "avail_page",
                        "total_virtual",
                        "avail_virtual",
                        "avail_extended",
                    ]
                ],
            ]

        status = MemoryStatus()
        status.length = ctypes.sizeof(status)
        if not ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(status)):
            raise OSError("Cannot read available host memory")
        return status.avail_phys
    fields = dict(
        line.split(":", 1) for line in Path("/proc/meminfo").read_text().splitlines()
    )
    return int(fields["MemAvailable"].split()[0]) * 1024


def admit(available, expected, reserve):
    return available >= expected + reserve


def command(args, **kwargs):
    return subprocess.run(
        args,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=kwargs.pop("timeout", 30),
        check=False,
        **kwargs,
    )


def checked_work(path):
    path = path.resolve()
    if not path.is_relative_to(WORK.resolve()) or path == WORK.resolve():
        raise ValueError(
            "Run directory must be strictly inside research/.work/simulator-evaluation"
        )
    return path


def copy_checkout(row, target):
    base = ROOT / row["path"]
    dirty = command(["git", "status", "--porcelain"], cwd=base)
    commit = command(["git", "rev-parse", "HEAD"], cwd=base)
    if (
        dirty.returncode
        or dirty.stdout.strip()
        or commit.stdout.strip() != row["commit"]
    ):
        raise ValueError("Upstream source checkout changed; refusing to evaluate it")
    names = command(["git", "ls-files", "-z"], cwd=base)
    if names.returncode:
        raise ValueError("Cannot enumerate the pinned source checkout")
    for name in names.stdout.split("\0"):
        if not name:
            continue
        source = base / name
        if not source.resolve().is_relative_to(base.resolve()):
            raise ValueError("Source link escapes the pinned repository")
        if (
            not source.is_file()
        ):  # Explicit sparse checkout: datasets are acquired separately.
            continue
        destination = checked_work(target / name)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)


def terminate_container(name, process):
    # Exact owned name, never compose down or enumeration of foreign containers.
    result = command(["docker", "rm", "-f", name], timeout=30)
    try:
        process.wait(timeout=10)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=10)
    return result.returncode == 0


def docker_memory(name):
    # Docker cgroup peak includes children of the test, rather than just its CLI.
    proc = command(
        ["docker", "exec", name, "cat", "/sys/fs/cgroup/memory.peak"], timeout=3
    )
    try:
        return int(proc.stdout.strip()) if proc.returncode == 0 else 0
    except ValueError:
        return 0


def phase(row, profile, stage, run, policy):
    phase_command = profile[stage]
    if stage != "install":
        phase_command = profile.get("runtime_prefix", "") + phase_command
    expected = profile.get(
        stage + "_admission_bytes", profile.get("admission_bytes", 512 * 1024**2)
    )
    available = free_memory()
    record = {
        "stage": stage,
        "command": phase_command,
        "status": "blocked",
        "host_available_bytes": available,
        "minimum_host_available_bytes": available,
        "admission_bytes": expected,
        "host_reserve_bytes": policy["host_reserve_bytes"],
        "peak_memory_bytes": 0,
        "seconds": 0,
        "exit_code": None,
        "data_scope": profile.get("data_scope", "unknown"),
    }
    if not policy.get("unrestricted_memory") and not admit(
        available, expected, policy["host_reserve_bytes"]
    ):
        record["reason"] = "host_memory_reserve"
        return record
    if shutil.disk_usage(WORK).free < policy["disk_reserve_bytes"]:
        record["reason"] = "disk_reserve"
        return record
    name = "aspa-sim-" + row["id"].lower() + "-" + uuid.uuid4().hex[:10]
    cache = WORK / "pip-cache"
    cache.mkdir(exist_ok=True)
    args = [
        "docker",
        "run",
        "--rm",
        "--name",
        name,
        "--label",
        "aspa.simulation.owner=simctl",
        "--cpus",
        str(policy["cpu_threads"]),
        "--pids-limit",
        "256",
        "-v",
        str(run) + ":/work",
        "-v",
        str(cache) + ":/pip-cache",
        "-w",
        "/work/source",
        "-e",
        "PIP_CACHE_DIR=/pip-cache",
        "-e",
        "TMPDIR=/work/tmp",
        "-e",
        "OMP_NUM_THREADS=4",
        "-e",
        "MKL_NUM_THREADS=4",
        "-e",
        "OPENBLAS_NUM_THREADS=4",
        "-e",
        "LP_NUM_THREADS=4",
        "-e",
        "LIBGL_ALWAYS_SOFTWARE=1",
        "-e",
        "NUMBA_NUM_THREADS=4",
        "-e",
        "MUJOCO_GL=egl",
        "-e",
        "CUDA_VISIBLE_DEVICES=",
        "-e",
        "HOME=/work/home",
        "-e",
        "MPLCONFIGDIR=/work/mpl",
        "-e",
        "XDG_CACHE_HOME=/work/cache",
        "-e",
        "JAX_PLATFORMS=cpu",
        "-e",
        "PYTHONHASHSEED=0",
        profile["image"],
        "sh",
        "-ec",
        phase_command,
    ]
    (run / "tmp").mkdir(exist_ok=True)
    if not policy.get("unrestricted_memory"):
        args[2:2] = [
            "--memory",
            str(policy["memory_bytes"]),
            "--memory-swap",
            str(policy["memory_bytes"]),
        ]
    if row.get("repository") == "TuragaLab/flyvis":
        # Exported worktrees lack Git metadata. This is a technical snapshot
        # version carrying the exact source commit, not an upstream release.
        args[args.index(profile["image"]) : args.index(profile["image"])] = [
            "-e",
            "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_FLYVIS=0+git." + row["commit"],
        ]
    record["docker_command"] = args
    deadline = (
        policy["install_seconds"]
        if stage == "install"
        else policy["smoke_seconds"]
        if stage == "smoke"
        else policy["functional_seconds"]
    )
    log = run / (stage + ".log")
    if log.exists():
        log = run / (stage + "-" + uuid.uuid4().hex[:8] + ".log")
    record["log"] = log.name
    started = time.monotonic()
    with log.open("w", encoding="utf-8", newline="\n") as stream:
        process = subprocess.Popen(args, stdout=stream, stderr=subprocess.STDOUT)
        reason = None
        try:
            while process.poll() is None:
                available_now = free_memory()
                record["minimum_host_available_bytes"] = min(
                    record["minimum_host_available_bytes"], available_now
                )
                if time.monotonic() - started >= deadline:
                    reason = "timeout"
                elif available_now < policy["host_reserve_bytes"]:
                    reason = "host_memory_reserve"
                if reason:
                    record["host_available_bytes_at_stop"] = available_now
                    record["termination_confirmed"] = terminate_container(name, process)
                    break
                record["peak_memory_bytes"] = max(
                    record["peak_memory_bytes"], docker_memory(name)
                )
                time.sleep(1)
        except (OSError, subprocess.SubprocessError) as exc:
            reason = "monitor_failure"
            record["monitor_error"] = str(exc)
            record["termination_confirmed"] = terminate_container(name, process)
    record.update(
        seconds=round(time.monotonic() - started, 3),
        exit_code=process.returncode,
        log_sha256=hashlib.sha256(log.read_bytes()).hexdigest(),
    )
    if reason:
        record.update(reason=reason, status="blocked")
    else:
        record.update(
            status="passed" if process.returncode == 0 else "failed",
            reason=None if process.returncode == 0 else "upstream_command_failed",
        )
    return record


def evaluate(row, profile, policy, resume=None):
    run = (
        checked_work(ROOT / resume)
        if resume
        else checked_work(
            WORK
            / row["id"]
            / (
                time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
                + "-"
                + uuid.uuid4().hex[:6]
            )
        )
    )
    previous = None
    if resume:
        if run.parent != WORK / row["id"]:
            raise ValueError("Resume path does not belong to this candidate")
        previous = load(run / "result.json")
        if (
            previous["commit"] != row["commit"]
            or previous["profile"]["image"] != profile["image"]
        ):
            raise ValueError("Resume commit or base image changed")
        if not any(
            p["stage"] == "install" and p["status"] == "passed"
            for p in previous["phases"]
        ):
            raise ValueError("Only a successfully installed environment can be resumed")
        if not (run / "dependencies.lock.txt").is_file():
            raise ValueError("Installed dependency lock is missing")
    else:
        run.mkdir(parents=True, exist_ok=False)
    result = {
        "repository": row["repository"],
        "commit": row["commit"],
        "run": run.relative_to(ROOT).as_posix(),
        "profile": profile,
        "policy": policy,
        "phases": [],
        "status": "blocked",
        "biological_validation": False,
        "human_ecap_model": False,
    }
    if previous:
        result["phases"] = [
            p
            for p in previous["phases"]
            if p["status"] == "passed"
            and (
                p["stage"] == "install"
                or (
                    p["stage"] in {"native_tests", "smoke"}
                    and p.get("command")
                    == profile.get("runtime_prefix", "") + profile[p["stage"]]
                )
            )
        ]
        result["prior_checks"] = previous.get("prior_checks", []) + [
            {
                k: v
                for k, v in p.items()
                if k in {"stage", "status", "reason", "log", "log_sha256"}
            }
            for p in previous["phases"]
            if p not in result["phases"]
        ]
    # Admission follows the next actual phase, including a resumed scenario.
    first_pending = next(
        (
            stage
            for stage in ["install", "native_tests", "smoke", "functional"]
            if profile.get(stage)
            and not any(
                p["stage"] == stage and p["status"] == "passed"
                for p in result["phases"]
            )
        ),
        "functional",
    )
    admission = profile.get(
        first_pending + "_admission_bytes",
        profile.get("admission_bytes", 512 * 1024**2),
    )
    # Avoid creating dependency/worktree copies for an inadmissible job.
    if not policy.get("unrestricted_memory") and not admit(
        free_memory(),
        admission,
        policy["host_reserve_bytes"],
    ):
        result["phases"].append(
            {
                "stage": first_pending,
                "status": "blocked",
                "reason": "host_memory_reserve",
                "host_available_bytes": free_memory(),
                "host_reserve_bytes": policy["host_reserve_bytes"],
                "admission_bytes": admission,
            }
        )
    else:
        if not previous:
            copy_checkout(row, run / "source")
        else:
            snapshot = load(WORK / row["id"] / "source-inventory.json")
            for relative, sha in snapshot["files"].items():
                source = checked_work(run / "source" / relative)
                if (
                    not source.is_file()
                    or hashlib.sha256(source.read_bytes()).hexdigest() != sha
                ):
                    raise ValueError(
                        "Resume source differs from the registered snapshot: "
                        + relative
                    )
        shutil.copytree(
            Path(__file__).with_name("probes"), run / "probes", dirs_exist_ok=True
        )
        if row["id"] == "SIM-003":
            from probes.infinite_sugar_assets import hydrate

            hydrate(run)
        for asset in profile.get("assets", []):
            source = checked_work(WORK / asset["source"])
            if (
                not source.is_file()
                or hashlib.sha256(source.read_bytes()).hexdigest() != asset["sha256"]
            ):
                result["phases"].append(
                    {
                        "stage": "asset_validation",
                        "status": "blocked",
                        "reason": "registered_asset_missing_or_hash_mismatch",
                    }
                )
                save(run / "result.json", result)
                return result
            destination = checked_work(run / "assets" / asset["destination"])
            destination.parent.mkdir(exist_ok=True)
            shutil.copy2(source, destination)
        for stage in ["install", "native_tests", "smoke", "functional"]:
            if previous and any(
                p["stage"] == stage and p["status"] == "passed"
                for p in result["phases"]
            ):
                continue
            if not profile.get(stage):
                result["phases"].append(
                    {
                        "stage": stage,
                        "status": "inapplicable",
                        "reason": profile.get(
                            stage + "_reason", "No native entry point registered"
                        ),
                    }
                )
                continue
            item = phase(row, profile, stage, run, policy)
            result["phases"].append(item)
            if item["status"] != "passed":
                break
    states = [p["status"] for p in result["phases"]]
    result["status"] = (
        "reproduced"
        if states and all(x == "passed" for x in states)
        else "partial"
        if "passed" in states
        else "blocked"
    )
    # A missing functionality scenario cannot be accepted as a reproduced simulator.
    if any(x == "inapplicable" for x in states) and result["status"] == "reproduced":
        result["status"] = "partial"
    save(run / "result.json", result)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=["preflight", "evaluate", "verify"])
    parser.add_argument("--id", help="SIM-xxx, omitted to evaluate sequentially")
    parser.add_argument(
        "--no-host-reserve",
        action="store_true",
        help="Explicitly disable the host RAM reserve for this invocation",
    )
    parser.add_argument(
        "--no-memory-limit",
        action="store_true",
        help="Attempt launches without a Docker RAM cap or host RAM admission gate",
    )
    parser.add_argument(
        "--resume",
        help="Relative .work run with a successful installation; requires --id",
    )
    args = parser.parse_args()
    if args.resume and (args.action != "evaluate" or not args.id):
        parser.error("--resume requires evaluate --id")
    registry = load(REGISTRY)
    policy = dict(registry["policy"])
    if args.no_host_reserve:
        policy["host_reserve_bytes"] = 0
    if args.no_memory_limit:
        policy["host_reserve_bytes"] = 0
        policy["unrestricted_memory"] = True
    if args.action == "preflight":
        report = {
            "host_available_bytes": free_memory(),
            "policy": registry["policy"],
            "docker": command(
                ["docker", "version", "--format", "{{.Server.Version}}"]
            ).stdout.strip(),
        }
        save(WORK / "preflight.json", report)
        print(json.dumps(report, indent=2))
    elif args.action == "evaluate":
        profiles = load(Path(__file__).with_name("profiles.json"))
        for row in registry["candidates"]:
            if args.id and row["id"] != args.id:
                continue
            profile = profiles.get(row["id"])
            if row["status"] != "attached" or not profile:
                print(
                    row["id"],
                    "blocked:",
                    row.get("evaluation", {}).get(
                        "reason", "Source or execution profile unavailable"
                    ),
                )
                continue
            result = evaluate(row, profile, policy, resume=args.resume)
            row["evaluation"] = {
                "status": result["status"],
                "result": result["run"] + "/result.json",
                "data_scope": profile.get("data_scope"),
                "phases": [
                    {
                        k: v
                        for k, v in p.items()
                        if k
                        in {
                            "stage",
                            "status",
                            "reason",
                            "seconds",
                            "peak_memory_bytes",
                            "termination_confirmed",
                            "host_available_bytes",
                            "minimum_host_available_bytes",
                            "host_available_bytes_at_stop",
                            "host_reserve_bytes",
                            "admission_bytes",
                        }
                    }
                    for p in result["phases"]
                ],
            }
            save(REGISTRY, registry)
            print(row["id"], result["status"], flush=True)
            if any(p.get("reason") == "host_memory_reserve" for p in result["phases"]):
                print("Queue stopped: host memory reserve", flush=True)
                break
    else:
        errors = []
        baseline = load(WORK / "baseline.json")
        for path, sha in baseline["protected"].items():
            if (
                not (ROOT / path).is_file()
                or hashlib.sha256((ROOT / path).read_bytes()).hexdigest() != sha
            ):
                errors.append("Protected content changed: " + path)
        candidates = registry["candidates"]
        for field in ("id", "path", "repository"):
            if len({row[field] for row in candidates}) != len(candidates):
                errors.append("Duplicate candidate " + field)
        modules = command(
            [
                "git",
                "config",
                "-f",
                ".gitmodules",
                "--get-regexp",
                r"^submodule\.simulation/",
            ],
            cwd=ROOT,
        )
        index = command(
            ["git", "ls-files", "--stage", "--", "simulation/sidecars"], cwd=ROOT
        )
        if modules.returncode or index.returncode:
            errors.append("Cannot read submodule registrations or Git index")
        module_fields = dict(line.split(" ", 1) for line in modules.stdout.splitlines())
        indexed = {}
        for line in index.stdout.splitlines():
            metadata, path = line.split("\t", 1)
            mode, sha, stage = metadata.split()
            indexed[path] = (mode, sha, stage)
        if set(indexed) != {row["path"] for row in candidates}:
            errors.append("Indexed sidecar set differs from the registry")
        canonical = {
            row["id"] for row in load(ROOT / "research/data/records.json")["sources"]
        }
        for row in registry["candidates"]:
            if not re.fullmatch(r"[a-f0-9]{40}", row.get("commit", "")):
                errors.append("Invalid commit: " + row["id"])
            if row.get("recorded_commit") and row["recorded_commit"] != row["commit"]:
                errors.append("Recorded baseline pin changed: " + row["id"])
            for source_id in row["source_ids"]:
                if source_id not in canonical:
                    errors.append("Unknown source: " + source_id)
            prefix = "submodule.simulation/" + row["id"]
            if (
                module_fields.get(prefix + ".path") != row["path"]
                or module_fields.get(prefix + ".url") != row["url"]
            ):
                errors.append("Submodule registration mismatch: " + row["id"])
            if indexed.get(row["path"]) != ("160000", row["commit"], "0"):
                errors.append("Gitlink mismatch: " + row["id"])
            if row["status"] != "attached":
                errors.append("Not attached: " + row["id"])
                continue
            base = ROOT / row["path"]
            actual = command(["git", "rev-parse", "HEAD"], cwd=base)
            if actual.returncode or actual.stdout.strip() != row["commit"]:
                errors.append("Commit mismatch: " + row["id"])
            clean = command(["git", "status", "--porcelain"], cwd=base)
            if clean.returncode or clean.stdout.strip():
                errors.append("Dirty source: " + row["id"])
        save(
            WORK / "integrity.json",
            {"errors": errors, "protected_files": len(baseline["protected"])},
        )
        print(
            json.dumps(
                {"errors": errors, "protected_files": len(baseline["protected"])},
                indent=2,
            )
        )
        if errors:
            raise SystemExit(1)


if __name__ == "__main__":
    main()
